name: e2e Tests

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: yarn
      - run: yarn build
      - run: npx playwright install --with-deps
      - run: yarn test:e2e
